### ISSUE TITLE
AutoencoderKLCogVideoX error

### ISSUE THREAD

**Issue by dcalabrez** [kijai/ComfyUI-CogVideoXWrapper#171]
Hi Kijai, I'm getting a brand new, showstopper error with CogVideoDecode and CogVideoImageInterpolationEncode (haven't tested all workflows yet):

`'AutoencoderKLCogVideoX' object has no attribute '_clear_fake_context_parallel_cache'`

Any ideas? It's happening right after hitting 100%. Windows 11, 24GB VRAM.

Thanks for any advice helping to solve this and your outstanding dedication to this project!

**Comment by dcalabrez** [comment]
I think this may have been diffuser-related as the error seems to be gone after the latest update (hopefully). Now getting a different error related to assembling the completed frames between CogVideoDecode and Video Combine, accompanied by a black output:

```
...videohelpersuite\nodes.py:102: RuntimeWarning: invalid value encountered in cast
  return tensor_to_int(tensor, 8).astype(np.uint8)
```

**Comment by monmonja** [comment]
Same here, updated diffuser and getting the same error on linux

**Comment by monmonja** [comment]
Managed to fix it, you have to go to the requirement.txt and instead of >=0.30.3 make it ==0.30.3, i also did the same with accelarate. Then pip install -r requirement.txt

**Comment by FDoKE** [comment]
@kijai can confirm too - not working on actual diffusers ==0.30.3 fixes the problem

**Comment by kijai** [comment]
> @kijai can confirm too - not working on actual diffusers ==0.30.3 fixes the problem

Or just update the nodes as I fixed diffusers 0.31.0 support when it came out already.
